#!/usr/bin/env python3
"""Pins requirements.in to exactly one wheel per platform: lock/<platform>.txt.

For each package and platform this picks the wheel pip itself would pick there (the best match in
packaging.tags' priority order for runtime.json's Python and wheel platform) and records its sha256
from PyPI's JSON API. Nothing is downloaded. The build installs with --require-hashes, so a lock
line is the whole trust decision for that file - review a lock diff like a code diff.

    python3 tools/lock.py            # rewrite lock/*.txt
    python3 tools/lock.py --check    # exit 1 if they are out of date (CI runs this)
"""
import json, os, re, sys, urllib.request

try:
    from packaging import tags
    from packaging.utils import canonicalize_name, parse_wheel_filename
except ImportError:                      # any Python with pip has a copy
    from pip._vendor.packaging import tags
    from pip._vendor.packaging.utils import canonicalize_name, parse_wheel_filename

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def requirements():
    out = []
    for line in open(os.path.join(ROOT, "requirements.in"), encoding="utf-8"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        m = re.fullmatch(r"([A-Za-z0-9._-]+)==([A-Za-z0-9.+!-]+)", line)
        if not m:
            sys.exit(f"requirements.in: '{line}' - every line must be an exact name==version pin")
        out.append((m.group(1), m.group(2)))
    return out


def supported(py, wheel_platform):
    """Tags in pip's preference order for this interpreter and platform."""
    if wheel_platform.startswith("macosx_"):
        _, major, minor, arch = wheel_platform.split("_", 3)
        plats = list(tags.mac_platforms((int(major), int(minor)), arch))
    else:
        plats = [wheel_platform]
    abi = f"cp{py[0]}{py[1]}"
    return list(tags.cpython_tags(py, [abi], plats)) + list(tags.compatible_tags(py, abi, plats))


def pick(name, version, ranked):
    with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=60) as r:
        files = json.load(r)["urls"]
    rank = {t: i for i, t in enumerate(ranked)}
    best = None
    for f in files:
        if not f["filename"].endswith(".whl") or f.get("yanked"):
            continue
        wname, wver, _, wtags = parse_wheel_filename(f["filename"])
        if canonicalize_name(wname) != canonicalize_name(name) or str(wver) != version:
            continue
        score = min((rank[t] for t in wtags if t in rank), default=None)
        if score is not None and (best is None or score < best[0]):
            best = (score, f)
    return best[1] if best else None


def render(platform, spec, py, reqs):
    ranked = supported(py, spec["wheel_platform"])
    lines = [f"# lock/{platform}.txt - generated by tools/lock.py from requirements.in; do not edit by hand.",
             f"# CPython {py[0]}.{py[1]}, {spec['wheel_platform']}: one wheel per package, installed with --no-deps --require-hashes."]
    missing = []
    for name, version in reqs:
        f = pick(name, version, ranked)
        if not f:
            missing.append(f"{name}=={version}")
            continue
        lines += [f"# {f['filename']} ({f['size'] / 1e6:.1f} MB)",
                  f"{name}=={version} --hash=sha256:{f['digests']['sha256']}"]
    if missing:
        sys.exit(f"{platform}: no wheel on PyPI for " + ", ".join(missing))
    return "\n".join(lines) + "\n"


def main():
    cfg = json.load(open(os.path.join(ROOT, "runtime.json"), encoding="utf-8"))
    py = tuple(int(x) for x in cfg["python"]["version"].split(".")[:2])
    reqs = requirements()
    stale = []
    for platform, spec in cfg["platforms"].items():
        text = render(platform, spec, py, reqs)
        path = os.path.join(ROOT, "lock", platform + ".txt")
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if "--check" in sys.argv:
            if old != text:
                stale.append(platform)
        elif old != text:
            open(path, "w", encoding="utf-8", newline="\n").write(text)
            print("wrote", os.path.relpath(path, ROOT))
        else:
            print("unchanged", os.path.relpath(path, ROOT))
    if stale:
        sys.exit("out of date: " + ", ".join(f"lock/{p}.txt" for p in stale) + " - run tools/lock.py")


if __name__ == "__main__":
    main()
